import type { Place } from "./types";

// Coordinates and price ranges below are desk research (Sep 2026), credited to
// the team "from the web". A Price Check made on the spot comes in through
// /contribute and replaces it (docs/adr/0005). Unchecked prices show "ยังไม่รู้ราคาจริง".
// Photos come from Wikimedia Commons; replace them with the team's own shots when you have them.
export const places: Place[] = [
  // การเดินทาง
  {
    id: "mrt-samyan",
    brand: "mrt",
    name: "MRT สามย่าน",
    category: "transport",
    lat: 13.7324,
    lng: 100.5294,
    summary: "ใกล้ฝั่งสามย่านสุด เดินใต้ดินทะลุเข้าสามย่านมิตรทาวน์ได้",
    photo: { file: "Exit no.2 Sam Yan MRT.jpg", alt: "ทางออก 2 สถานี MRT สามย่าน" },
    knowhow: [
      "บัตรเครดิตหรือเดบิตที่มีรูปคลื่นแตะจ่าย แตะผ่านประตูได้เลย ไม่ต้องซื้อเหรียญ",
      "ใช้บัตรใบเดียวกันแตะทั้งตอนเข้าและตอนออก",
      "ไม่มีบัตรแบบนี้ ก็ซื้อเหรียญเที่ยวเดียวที่ตู้หรือห้องขายตั๋ว",
      "ขึ้นทางออก 2 จะโผล่ที่จามจุรีสแควร์ เดินเข้าจุฬาฯ ได้เลย หรือต่อรถป๊อปสาย\u00a04 ที่สามย่านมิตรทาวน์",
    ],
    cautions: ["บัตร MRT แบบเดิมและ MRT Plus ใช้ไม่ได้แล้วตั้งแต่ 1 มิ.ย. 2569"],
    toChula: "ขึ้นทางออก 2 แล้วเดินเข้าจุฬาฯ ได้เลย หรือต่อรถป๊อปสาย\u00a04 ฟรีที่สามย่านมิตรทาวน์ แต่วันเสาร์สาย\u00a04 ไม่วิ่ง",
    guides: ["to-chula"],
    price: { min: 17, max: 44, per: "ต่อเที่ยว", checked: { on: "2026-09", by: "ทีมตั้งหลัก", how: "web" } },
  },
  {
    id: "bts-siam",
    brand: "bts",
    name: "BTS สยาม",
    category: "transport",
    lat: 13.7456,
    lng: 100.5347,
    summary: "ที่เปลี่ยนสายสุขุมวิทกับสีลม จะเดินหรือต่อรถป๊อปเข้าจุฬาฯ ก็ได้",
    photo: { file: "Siam BTS Station, view from Siam Paragon.jpg", alt: "สถานี BTS สยาม มองจากสยามพารากอน" },
    knowhow: [
      "ขึ้นทุกวันก็ทำบัตร Rabbit ไปเลย ไม่ต้องต่อคิวตู้ทุกเช้า",
      "ช่วง 7:30–9:00 คนแน่นมาก เผื่อเวลาไว้อย่างน้อย 15 นาที",
    ],
    cautions: ["ยืนชิดขวาบนบันไดเลื่อน ฝั่งซ้ายเว้นให้คนเดินขึ้น"],
    toChula: "ลงทางออก 2 ไปป้ายรถป๊อป \"ลิโด้\" หน้า 7-Eleven ขึ้นสาย\u00a01 ที่วิ่ง จ.–ส. หรือสาย\u00a04 ที่วิ่ง จ.–ศ. ฟรีทั้งคู่ ลงที่ศาลาพระเกี้ยว",
    guides: ["to-chula", "rabbit"],
    price: { min: 17, max: 47, per: "ต่อเที่ยว", checked: { on: "2026-09", by: "ทีมตั้งหลัก", how: "web" } },
  },
  {
    id: "bts-national-stadium",
    brand: "bts",
    name: "BTS สนามกีฬาแห่งชาติ",
    category: "transport",
    lat: 13.7466,
    lng: 100.529,
    summary: "ใกล้ฝั่งบรรทัดทองกับหอแถวนั้น",
    photo: { file: "Early morning in National Stadium BTS sky train station, Bangkok, Thailand.jpg", alt: "สถานี BTS สนามกีฬาแห่งชาติตอนเช้า" },
    knowhow: ["ลงสถานีนี้แล้วเดินเลียบถนนบรรทัดทองลงมาทางจุฬาฯ ได้"],
    toChula: "ขึ้นรถป๊อปสาย\u00a02 ฟรี วิ่ง จ.–ส. หรือเดินเลียบถนนบรรทัดทองลงมาก็ได้",
    guides: ["to-chula", "rabbit"],
    price: { min: 17, max: 47, per: "ต่อเที่ยว", checked: { on: "2026-09", by: "ทีมตั้งหลัก", how: "web" } },
  },

  // ของกิน
  {
    id: "samyan-mitrtown-food",
    name: "ศูนย์อาหาร สามย่านมิตรทาวน์",
    category: "food",
    lat: 13.7338,
    lng: 100.5282,
    summary: "Samyan Food Legends ชั้น 4 แอร์เย็น ร้านให้เลือกเยอะ เปิด 10:00 ถึงราว 22:00",
    guides: ["eat-cheap", "late-night"],
    photo: { file: "Samyan Mitrtown สามย่านมิตรทาวน์.jpg", alt: "อาคารสามย่านมิตรทาวน์" },
    knowhow: [
      "ไม่ต้องแลกบัตรแล้ว สแกน QR จ่ายที่ร้านได้เลย หรือจ่ายด้วย TrueMoney",
      "ศูนย์อาหารปิดพร้อมห้าง หิวดึกลงไปโซน 24 ชั่วโมงชั้นล่าง",
    ],
    price: { min: 60, max: 150, per: "ต่อจาน", checked: { on: "2026-09", by: "ทีมตั้งหลัก", how: "web" } },
  },
  {
    id: "samyan-market",
    name: "ตลาดสามย่าน",
    category: "food",
    lat: 13.7371,
    lng: 100.5253,
    summary: "ตลาดสดกับร้านอาหาร ชั้นบนมีร้านข้าวให้เลือกเยอะ",
    guides: ["eat-cheap"],
    knowhow: ["ร้านข้าวราดแกงคิดตามจำนวนกับข้าวที่ตัก บอกก่อนว่าจะเอากี่อย่าง"],
    price: { min: 50, max: 80, per: "ต่อจาน", checked: { on: "2026-09", by: "ทีมตั้งหลัก", how: "web" } },
  },
  {
    id: "banthat-thong",
    name: "ถนนบรรทัดทอง",
    category: "food",
    lat: 13.742,
    lng: 100.5222,
    summary: "ร้านอาหารเรียงยาวทั้งถนน คนเยอะตั้งแต่เย็นยันดึก",
    guides: ["eat-cheap"],
    photo: { file: "Banthat Thong Road.jpg", alt: "ถนนบรรทัดทอง" },
    knowhow: ["หลายร้านดังคิวยาวช่วงหัวค่ำ ถ้าหิวจริงให้มาก่อน 18:00 หรือหลัง 20:30"],
    cautions: ["ร้านที่ขึ้นรีวิวบ่อยมักแพงกว่าร้านข้างๆ ที่คนแถวนั้นกิน"],
    price: { min: 60, max: 200, per: "ต่อจาน", checked: { on: "2026-09", by: "ทีมตั้งหลัก", how: "web" } },
  },
  {
    id: "niyom-paktai",
    name: "นิยมปักษ์ใต้ บรรทัดทอง",
    category: "food",
    // Pin is an estimate from the address; check it on the spot.
    lat: 13.7375,
    lng: 100.5225,
    summary: "ร้านอาหารใต้บนถนนบรรทัดทอง ฝั่งตรงข้ามจุฬาฯ ซอย 34 เปิดทุกวันตั้งแต่ 11:00",
    photo: { file: "Kaeng tai pla.JPG", alt: "แกงไตปลา อาหารใต้ เป็นภาพประกอบ ไม่ใช่ของร้านนี้" },
    knowhow: ["เผ็ดแบบใต้จริง กินเผ็ดไม่เก่งก็บอกลดเผ็ดตอนสั่ง", "ราคาต่อจานแรงกว่าร้านข้าวทั่วไป ชวนเพื่อนไปหลายคนแล้วแบ่งกันกินคุ้มกว่า"],
    price: { min: 120, max: 250, per: "ต่อจาน", checked: { on: "2026-09", by: "ทีมตั้งหลัก", how: "web" } },
    homeTaste: "ใต้",
  },
  {
    id: "somtam-chula-20",
    name: "ส้มตำเจ๊อ้อย จุฬาฯ ซอย 20",
    category: "food",
    // Pin is an estimate from the address; check it on the spot.
    lat: 13.739,
    lng: 100.5235,
    summary: "ส้มตำโต๊ะแดงในจุฬาฯ ซอย 20 ใกล้อุทยาน 100 ปี เปิดเย็นถึงดึก 16:30–23:30",
    photo: { file: "Som Tam green papaya salad, Bangkok, Thailand.jpg", alt: "ส้มตำ เป็นภาพประกอบ ไม่ใช่ของร้านนี้" },
    knowhow: ["ร้านเปิดตอนเย็น มาหลังเลิกเรียนหรือหลังซ้อมได้พอดี", "คนชอบสั่งส้มตำไทยกับคอหมูย่าง"],
    price: { min: 50, max: 150, per: "ต่อจาน", checked: { on: "2026-09", by: "ทีมตั้งหลัก", how: "web" } },
    homeTaste: "อีสาน",
  },
  // PROTOTYPE (home-taste): more team picks per region, from .scratch/more-know-how/research-food-health.md §3.
  // Pins are estimates from the address; prices are from the web. Folded in properly if the prototype wins.
  {
    id: "khao-soi-doi-kham",
    photo: { file: "Khanom chin nam ngiao.jpg", alt: "ขนมจีนน้ำเงี้ยว เป็นภาพประกอบ ไม่ใช่ของร้านนี้" },
    name: "ข้าวซอยดอยคำ จุฬาฯ ซอย 14",
    category: "food",
    lat: 13.743,
    lng: 100.5226,
    summary: "ข้าวซอยกับขนมจีนน้ำเงี้ยว ห้องแถวคูหาเดียวในซอยจุฬาฯ 14 เปิดทุกวัน 11:00–21:00",
    knowhow: ["ข้าวซอยเนื้อชามละ 79 บาท", "มีข้าวกั้นจิ้นกับไส้อั่วน้ำพริกหนุ่มด้วย"],
    price: { min: 79, max: 120, per: "ต่อชาม", checked: { on: "2026-10", by: "ทีมตั้งหลัก", how: "web" } },
    homeTaste: "เหนือ",
  },
  {
    id: "lamduan-faham",
    photo: { file: "Khao soi Chiang Mai.jpg", alt: "ข้าวซอย เป็นภาพประกอบ ไม่ใช่ของร้านนี้" },
    name: "ข้าวซอยลำดวนฟ้าฮ่าม บรรทัดทอง",
    category: "food",
    lat: 13.7452,
    lng: 100.5217,
    summary: "สาขาร้านข้าวซอยเก่าแก่ของเชียงใหม่ ตรงข้ามสเตเดียมวัน เปิดทุกวัน 10:00–20:30",
    knowhow: ["ร้านดั้งเดิมอยู่เชียงใหม่มากว่า 80 ปี", "ข้าวซอยเนื้อกับข้าวซอยกระดูกอ่อนเป็นจานที่คนสั่งกัน"],
    price: { min: 69, max: 129, per: "ต่อชาม", checked: { on: "2026-10", by: "ทีมตั้งหลัก", how: "web" } },
    homeTaste: "เหนือ",
  },
  {
    id: "hom-duan",
    photo: { file: "Kaeng hangle.jpg", alt: "แกงฮังเล เป็นภาพประกอบ ไม่ใช่ของร้านนี้" },
    name: "หอมด่วน สามย่านมิตรทาวน์",
    category: "food",
    lat: 13.7339,
    lng: 100.5283,
    summary: "อาหารเหนือ ชั้น G สามย่านมิตรทาวน์ น้ำพริกหนุ่ม น้ำพริกอ่อง แกงฮังเล เปิด 10:00–22:00",
    knowhow: ["ขนมจีนน้ำเงี้ยวชามละ 75 บาท ข้าวซอยกับแกงฮังเลราว 140"],
    price: { min: 75, max: 140, per: "ต่อจาน", checked: { on: "2026-10", by: "ทีมตั้งหลัก", how: "web" } },
    homeTaste: "เหนือ",
  },
  {
    id: "pa-khao",
    photo: { file: "Sai krok Isan yai.jpg", alt: "ไส้กรอกอีสาน เป็นภาพประกอบ ไม่ใช่ของร้านนี้" },
    name: "พาข้าว บรรทัดทอง",
    category: "food",
    lat: 13.744,
    lng: 100.5222,
    summary: "ส้มตำสายปลาร้ากับไส้กรอกอีสาน แยกซอยจุฬาฯ 12 เปิดถึงห้าทุ่ม",
    knowhow: ["ตำเส้นเล็ก 59 บาท ไส้กรอกอีสานชุดเล็ก 125", "คิวยาวช่วงเย็น"],
    price: { min: 59, max: 125, per: "ต่อจาน", checked: { on: "2026-10", by: "ทีมตั้งหลัก", how: "web" } },
    homeTaste: "อีสาน",
  },
  {
    id: "kham-paeng",
    photo: { file: "Lap mu isan.JPG", alt: "ลาบหมู เป็นภาพประกอบ ไม่ใช่ของร้านนี้" },
    name: "คำแพง ซอยจุฬาฯ 16",
    category: "food",
    lat: 13.741,
    lng: 100.5232,
    summary: "อาหารอีสานรสมือคนอุดรฯ ซอยจุฬาฯ 16 ราคาแรงหน่อย ไปเป็นกลุ่มคุ้มกว่า",
    knowhow: ["ไก่ทอดเกลือ 249 บาท", "เปิดถึงห้าทุ่ม ศุกร์ถึงอาทิตย์ถึงเที่ยงคืน"],
    price: { min: 120, max: 250, per: "ต่อจาน", checked: { on: "2026-10", by: "ทีมตั้งหลัก", how: "web" } },
    homeTaste: "อีสาน",
  },
  {
    id: "sri-kamin",
    photo: { file: "Khao yam.jpg", alt: "ข้าวยำ เป็นภาพประกอบ ไม่ใช่ของร้านนี้" },
    name: "ศรีขมิ้น สวนหลวงสแควร์",
    category: "food",
    lat: 13.743,
    lng: 100.5248,
    summary: "อาหารใต้ ขนมจีนแกงปู ใบเหลียงผัดไข่ ข้าวยำ สวนหลวงสแควร์ เปิดทุกวัน 11:00–22:00",
    knowhow: ["ใบเหลียงผัดไข่ 165 บาท แกงส้มปลากะพง 290", "ไปหลายคนแล้วแบ่งกันกินคุ้มกว่า"],
    price: { min: 80, max: 290, per: "ต่อจาน", checked: { on: "2026-10", by: "ทีมตั้งหลัก", how: "web" } },
    homeTaste: "ใต้",
  },
  {
    id: "mae-duen",
    name: "ขนมไทยแม่เดือน ซอยจุฬาฯ 16",
    category: "food",
    lat: 13.7422,
    lng: 100.5224,
    summary: "ขนมไทยสูตรคุณยายจากตลาดสามชุก สุพรรณบุรี ขนมถ้วย ขนมใส่ไส้ เม็ดขนุน คั้นกะทิเอง",
    photo: { file: "Khanom thuay.jpg", alt: "ขนมถ้วย เป็นภาพประกอบ ไม่ใช่ของร้านนี้" },
    knowhow: ["ขนมไทยกว่า 50 อย่าง บางอย่างชิ้นละ 15 บาท", "เป็นร้านขนม ไม่ใช่ร้านกับข้าว แวะซื้อกลับห้องได้"],
    // Hours (10:00–24:00) and the khanom thuay price (40 or 60) conflict between sources: estimates.
    price: { min: 15, max: 60, per: "ต่อชิ้นหรือกล่อง", checked: { on: "2026-10", by: "ทีมตั้งหลัก", how: "web" } },
    homeTaste: "กลาง",
  },
  {
    id: "sen-sukho",
    name: "เส้นสุโข ก๋วยเตี๋ยวสุโขทัยแม่บุญรอด",
    category: "food",
    lat: 13.735,
    lng: 100.5268,
    summary: "ก๋วยเตี๋ยวสุโขทัย หมูแดง ถั่วฝักยาว ถั่วลิสง ที่ U-Center ซอยจุฬาฯ 42 นิสิตจุฬาฯ ลด 5%",
    knowhow: ["ชามละ 75 บาท", "เปิดทุกวัน 11:00 ปิดราวหกโมงครึ่งถึงทุ่มครึ่ง"],
    price: { min: 75, max: 80, per: "ต่อชาม", checked: { on: "2026-10", by: "ทีมตั้งหลัก", how: "web" } },
    homeTaste: "กลาง",
  },
  {
    id: "kong-tui-bangtan",
    name: "ก๋งตุ๋ย ไก่ย่างบางตาล ราชบุรี",
    category: "food",
    lat: 13.7366,
    lng: 100.5252,
    summary: "ไก่ย่างบางตาลสูตรราชบุรี หมักขมิ้นจนเหลือง ซอยจุฬาฯ 11 ตรงข้ามโจ๊กสามย่าน เปิดเช้าถึงบ่ายสอง",
    photo: { file: "Gaiyangtaladdonwai06.jpg", alt: "ไก่ย่าง เป็นภาพประกอบ ไม่ใช่ของร้านนี้" },
    knowhow: ["ไก่ครึ่งตัว 90 บาท ส้มตำไทย 40", "ปิดวันจันทร์ ไปก่อนบ่ายสอง"],
    price: { min: 40, max: 90, per: "ต่อจาน", checked: { on: "2026-10", by: "ทีมตั้งหลัก", how: "web" } },
    homeTaste: "ตะวันตก",
  },

  {
    id: "sor-thor-food-court",
    name: "ศูนย์อาหารตึก สธ. โรงพยาบาลจุฬาฯ",
    category: "food",
    // Pin is an estimate inside the hospital grounds; check on the spot.
    lat: 13.7318,
    lng: 100.5352,
    summary: "ที่กินถูกที่เปิดวันเสาร์–อาทิตย์ ตอนโรงอาหารคณะปิด ชั้น 2 อาคาร ส.ธ.",
    knowhow: [
      "เปิดจันทร์–ศุกร์ 6:00–17:00 เสาร์–อาทิตย์ 6:00–15:00",
      "ร้านติดธงฟ้า ราคาคุมไว้ มีอาหารมังสวิรัติกับอาหารมุสลิม",
      "นิสิตกับคนทั่วไปเข้ากินได้ ไม่ต้องเป็นคนไข้",
    ],
    cautions: ["คนไข้กับญาติเยอะช่วงเที่ยง ไปก่อน 11:00 หรือหลัง 13:00"],
    guides: ["eat-cheap"],
    // Price is an estimate for a plate at a blue-flag shop.
    price: { min: 40, max: 60, per: "ต่อจาน", checked: { on: "2026-10", by: "ทีมตั้งหลัก", how: "web" } },
  },
  {
    id: "jae-oh",
    name: "เจ๊โอว ซอยจุฬาฯ 22",
    category: "food",
    // Pin is an estimate from the address; check it on the spot.
    lat: 13.7395,
    lng: 100.5223,
    summary: "ข้าวต้มกับมาม่าโอ้โห เปิดราว 16:30 ถึงเที่ยงคืน ของกินดึกที่คนแถวนี้รู้จัก",
    knowhow: [
      "จองคิวล่วงหน้าหนึ่งวันทางโทรศัพท์ได้ที่ 06-4118-5888 รับชั่วโมงละไม่กี่คิว",
      "ไม่ได้จองก็มาหลัง 21:00 คิวสั้นลง",
    ],
    cautions: ["หัวค่ำราว 19:00 คิวยาวมาก ถ้าหิวจริงอย่าเพิ่งมาช่วงนี้"],
    guides: ["late-night"],
    // Price is an estimate; sources gave none.
    price: { min: 80, max: 200, per: "ต่อจาน", checked: { on: "2026-10", by: "ทีมตั้งหลัก", how: "web" } },
  },
  {
    id: "asawin-boat-noodles",
    name: "ก๋วยเตี๋ยวเรืออัศวิน บรรทัดทอง",
    category: "food",
    // Pin is an estimate from the address; check it on the spot.
    lat: 13.7435,
    lng: 100.5221,
    summary: "ก๋วยเตี๋ยวเรือ เปิดทุกวัน 11:00 ถึงเที่ยงคืน ระหว่างซอยจุฬาฯ 12 กับ 14",
    knowhow: ["เส้นเล็กน้ำตกเป็นชามที่คนสั่งกันบ่อย", "เปิดถึงเที่ยงคืน อ่านหนังสือเสร็จดึกๆ ยังมากินทัน"],
    guides: ["late-night"],
    price: { min: 69, max: 89, per: "ต่อชาม", checked: { on: "2026-09", by: "ทีมตั้งหลัก", how: "web" } },
  },

  // สุขภาพ
  {
    id: "chula-hospital",
    icon: "sick",
    name: "โรงพยาบาลจุฬาลงกรณ์",
    category: "health",
    lat: 13.731,
    lng: 100.5362,
    // The ER is what people come here for at night, so it leads; it isn't a caution (UX audit 7, U2).
    summary: "ห้องฉุกเฉินเปิด 24 ชั่วโมง ชั้น 1 อาคาร ภ.ป.ร. ฝั่งถนนราชดำริ ไปเองไม่ไหวโทร 1669",
    photo: { file: "King Chulalongkorn Memorial Hospital and MDCU Chulalongkorn University.jpg", alt: "โรงพยาบาลจุฬาลงกรณ์" },
    knowhow: [
      "โรงพยาบาลใหญ่ใกล้มหาลัย ไว้ตอนเป็นหนักหรือต้องหาหมอเฉพาะทาง",
      "ถ้าไม่ฉุกเฉิน ไปศูนย์บริการสุขภาพ จุฬาฯ ที่อาคารจามจุรี 9 ชั้น 2 ก่อน นิสิตไม่เสียเงิน",
      "พกบัตรประชาชนกับบัตรนิสิตไปด้วยทุกครั้ง",
      "คลินิกนอกเวลาเปิดจันทร์–ศุกร์ 16:00–20:00 เสาร์–อาทิตย์ 8:00–12:00 แต่ต้องจ่ายเอง ใช้บัตรทองไม่ได้",
    ],
    guides: ["sick", "rights"],
  },
  {
    id: "cu-health-service",
    name: "ศูนย์บริการสุขภาพ จุฬาฯ",
    category: "health",
    icon: "sick",
    lat: 13.736,
    lng: 100.5257,
    // Hours lead: it's closed at night, which is when people look (UX audit 7, U2).
    summary: "ไม่สบายแต่ไม่ฉุกเฉิน มาที่นี่ก่อน เปิด จ.–ศ. 8:00–15:30 เที่ยงปิดพัก อยู่อาคารจามจุรี 9 ชั้น 2 นิสิตไม่เสียเงิน",
    knowhow: [
      "พกบัตรนิสิตไปด้วย",
      "เปิดวันจันทร์–ศุกร์ 8:00–11:30 และ 13:00–15:30 น. ปิดพักเที่ยง โทรถามก่อนได้ที่ 02-218-0568",
      "เลยเวลานี้แล้ว ไปห้องปฐมพยาบาลที่หอพักนิสิตชวนชม ดูในคู่มือ \"ไม่สบาย ไปไหนดี\"",
    ],
    cautions: ["เวลานี้เอามาจากเว็บจุฬาฯ อาจเปลี่ยนได้ โทรเช็กก่อนไปที่ 02-218-0568"],
    guides: ["sick"],
  },

  {
    id: "bks-5",
    icon: "sick",
    name: "ศูนย์บริการสาธารณสุข 5 จุฬาลงกรณ์",
    category: "health",
    // Pin from a map listing's snippet; soi Chula 36 may sit further south. Check on the spot.
    lat: 13.7405,
    lng: 100.5255,
    summary: "ศูนย์สุขภาพของ กทม. ที่ใกล้จุฬาฯ สุด ใช้บัตรทองด้วยบัตรประชาชนใบเดียว ซอยจุฬาฯ 36 เปิด จ.–ศ. 8:00–16:00",
    knowhow: [
      "บัตรทองยังไม่ได้ย้ายมากรุงเทพฯ ก็รักษาที่นี่ได้ ไม่ต้องมีใบส่งตัว",
      "เข้าทางซอยจุฬาฯ 5 ฝั่งถนนพระราม 4 ได้ด้วย",
      "โทรถามก่อนไปได้ที่ 02-214-1057",
    ],
    cautions: ["ไม่เปิดเย็นและวันหยุด เย็นวันธรรมดาไปศูนย์บริการสาธารณสุข 16 ลุมพินี เปิดถึง 20:00"],
    guides: ["rights", "sick"],
  },
  {
    id: "chuan-chom-first-aid",
    icon: "sick",
    name: "ห้องปฐมพยาบาล หอพักนิสิตชวนชม",
    category: "health",
    // Pin is an estimate for the dorm; check on the spot.
    lat: 13.7383,
    lng: 100.5267,
    summary: "ไม่สบายตอนกลางคืนแต่ไม่ฉุกเฉิน มาที่นี่ เปิดทุกวัน 18:00–06:00 นิสิตจุฬาฯ ทุกคนใช้ได้",
    knowhow: [
      "เป็นของศูนย์บริการสุขภาพ จุฬาฯ ดูแลเบื้องต้น มีรถพยาบาล",
      "ไม่ได้พักหอในก็มาได้ พกบัตรนิสิต",
      "โทรบอกก่อนไปที่ 09-1761-0988",
    ],
    cautions: ["ถ้าหายใจไม่ออก เจ็บหน้าอก หรือหมดสติ ไม่ต้องมาที่นี่ โทร 1669 เลย"],
    guides: ["sick"],
  },
  {
    id: "bw-drugs-chula-16",
    icon: "sick",
    name: "ร้านยา B&W Drugs ซอยจุฬาฯ 16",
    category: "health",
    // Pin is an estimate from the address; check it on the spot.
    lat: 13.7418,
    lng: 100.5226,
    summary: "ร้านยาที่เปิดดึกแถวบรรทัดทอง ทุกวัน 15:00–23:00",
    knowhow: [
      "เล่าอาการให้เภสัชฟังได้เลย ไม่ต้องมีใบหมอ",
      "บอกด้วยว่าแพ้ยาอะไร",
      "โทรถามก่อนว่ามียาที่ต้องการไหมได้ที่ 083-808-7766",
    ],
    cautions: ["แถวนี้ไม่มีร้านยาเปิด 24 ชั่วโมง เลย 23:00 แล้วเซเว่นขายได้แค่ยาสามัญอย่างพาราเซตามอล"],
    guides: ["sick"],
  },

  // งานบ้าน
  {
    // The id predates the name; Notes may point at it, so it stays.
    id: "samyan-mitrtown-supermarket",
    name: "บิ๊กซี ฟู้ดเพลส สามย่านมิตรทาวน์",
    category: "household",
    lat: 13.7334,
    lng: 100.5289,
    summary: "ซูเปอร์ฯ เปิด 24 ชั่วโมง ชั้น B1 ดึกแค่ไหนก็มาซื้อน้ำแพ็ค ผงซักฟอก ของใช้เข้าห้องได้",
    knowhow: [
      "ซื้อน้ำดื่มแพ็คใหญ่ถูกกว่าซื้อขวดเดี่ยวจากร้านสะดวกซื้อทุกวัน",
      "ครึ่งร้านเป็นของสด ของใช้ในบ้านมีไม่เยอะเท่าบิ๊กซีใหญ่ หาไม่เจอลองไดโซะชั้นเดียวกัน",
      "ห้างปิด 22:00 แต่โซน 24 ชั่วโมงยังเปิด เข้าทางประตูโซนนั้น",
    ],
    guides: ["drinking-water"],
  },
  {
    id: "otteri-im-park",
    icon: "laundry",
    name: "Otteri ไอแอมปาร์ค",
    category: "household",
    lat: 13.74,
    lng: 100.5253,
    summary: "ร้านซักผ้าหยอดเหรียญ เปิด 24 ชั่วโมง มีเครื่องอบ อยู่ไอแอมปาร์ค ซอยจุฬาฯ 9 ข้างอุทยาน 100 ปี",
    knowhow: [
      "มีเครื่องแลกเหรียญ รับแบงก์ 20 50 100 และขายน้ำยาซักผ้ากับน้ำยาปรับผ้านุ่มในร้าน",
      "ซักรอบหนึ่งราว 30 นาที ขึ้นไปนั่งร้านกาแฟข้างบนรอได้",
      "Lotus's go fresh อยู่ตึกเดียวกัน ซักผ้าไปซื้อของไป",
    ],
    cautions: ["โปรซักหลังเที่ยงคืนลด 10 บาท หมดไปตั้งแต่ เม.ย. 2568 แล้ว อย่าเชื่อรีวิวเก่า"],
    guides: ["coin-laundry"],
    price: { min: 40, max: 60, per: "ต่อรอบซัก", checked: { on: "2024-01", by: "ทีมตั้งหลัก", how: "web" } },
  },
  {
    id: "water-centenary-park",
    icon: "water",
    name: "ตู้กดน้ำฟรี อุทยาน 100 ปี จุฬาฯ",
    category: "household",
    // Pin is the park's centre; the dispenser is by the Cha Tra Mue shop. Check on the spot.
    lat: 13.7394,
    lng: 100.5242,
    summary: "ตู้กดน้ำดื่มฟรีของ PMCU ลานข้างร้านชาตรามือ พกขวดไปเติมได้",
    knowhow: [
      "ไม่ต้องจ่ายอะไร พกขวดหรือกระบอกน้ำไปเอง",
      "ใต้อาคาร U-Center ฝั่งสามย่านก็มีอีกตู้",
    ],
    cautions: ["เติมได้ทีละขวด จะเอาไปใช้ทั้งห้องยังต้องซื้อน้ำแพ็คหรือติดเครื่องกรอง"],
    guides: ["drinking-water"],
  },
  {
    id: "water-u-center",
    icon: "water",
    name: "ตู้กดน้ำฟรี ใต้อาคาร U-Center",
    category: "household",
    lat: 13.735,
    lng: 100.527,
    summary: "ตู้กดน้ำดื่มฟรีของ PMCU ใต้ U-Center ซอยจุฬาฯ 42 ฝั่งสามย่าน",
    knowhow: ["ตึกเดียวกันมีเซเว่นกับธนาคาร แวะเติมน้ำตอนกดเงินได้เลย"],
    guides: ["drinking-water"],
  },
  {
    id: "lotus-chamchuri",
    name: "Lotus's go fresh จามจุรีสแควร์",
    category: "household",
    lat: 13.7328,
    lng: 100.5306,
    summary: "ซูเปอร์ฯ ขนาดกลางชั้นใต้ดิน ลง MRT สามย่านแล้วเดินเข้าได้ไม่ต้องขึ้นข้างบน",
    knowhow: [
      "ผักแบ่งขายเป็นกำเล็ก ชั่งน้ำหนักเอาได้ อยู่คนเดียวซื้อพอดีกิน ไม่เหลือทิ้ง",
      "พกถุงผ้าไปเอง",
    ],
    // Hours conflict between sources (to 21:00 or 22:00): estimate, check on the spot.
    cautions: ["เปิด 7:00 ถึงราว 21:00–22:00 จะไปดึกโทรถามก่อน"],
  },
  {
    id: "lotus-im-park",
    name: "Lotus's go fresh ไอแอมปาร์ค",
    category: "household",
    // Same building as Otteri; pin is an estimate.
    lat: 13.7401,
    lng: 100.5255,
    summary: "ซูเปอร์ฯ เล็กฝั่งบรรทัดทอง เปิด 10:00–21:00 ทุกวัน ตึกเดียวกับร้านซักผ้า Otteri",
    knowhow: ["ของใช้ประจำวัน ทิชชู่ น้ำยาล้างจาน มีครบ ไม่ต้องข้ามไปห้าง"],
    guides: ["coin-laundry"],
  },
  {
    id: "daiso-samyan",
    name: "ไดโซะ สามย่านมิตรทาวน์",
    category: "household",
    lat: 13.7333,
    lng: 100.5287,
    summary: "ของจุกจิกเข้าห้อง กล่อง ไม้แขวน ที่คว่ำจาน อยู่ชั้น B1",
    knowhow: [
      "ของส่วนใหญ่ราคาเดียว เริ่ม 60 บาท",
      "ย้ายเข้าหอใหม่ มาที่นี่ทีเดียวได้ของจัดห้องเกือบครบ",
    ],
    cautions: ["ไม่ใช่ทุกชิ้นราคา 60 บาท ดูป้ายก่อนหยิบ บางอย่างซื้อซูเปอร์ฯ ถูกกว่า"],
    price: { min: 60, max: 60, per: "ขึ้นไป ต่อชิ้น", checked: { on: "2026-09", by: "ทีมตั้งหลัก", how: "web" } },
  },
  {
    id: "mrdiy-mbk",
    name: "MR.DIY เอ็มบีเค",
    category: "household",
    // MBK's pin is an estimate, next to BTS National Stadium.
    lat: 13.7446,
    lng: 100.53,
    summary: "ของใช้ในบ้านกับเครื่องมือช่างราคาถูก ปลั๊กพ่วง หลอดไฟ ไขควง อยู่ MBK ชั้น 5",
    knowhow: [
      "ไฟในห้องเสีย ปลั๊กไม่พอ มาที่นี่ได้ของถูกกว่าห้างอื่นแถวนี้",
      "ขึ้น BTS สนามกีฬาแห่งชาติ แล้วเดินสะพานเชื่อมเข้า MBK ได้",
    ],
    cautions: ["จะซ่อมอะไรที่ติดกับห้อง เช่น ไฟเพดาน ก๊อกน้ำ แจ้งหอก่อน อย่าเพิ่งซ่อมเอง"],
    // Price is an estimate for small items like a plug or a bulb.
    price: { min: 30, max: 300, per: "ต่อชิ้น", checked: { on: "2026-10", by: "ทีมตั้งหลัก", how: "web" } },
  },
  {
    id: "magnano-samyan",
    icon: "key",
    name: "แมกนาโน่ สามย่านมิตรทาวน์",
    category: "household",
    lat: 13.7335,
    lng: 100.529,
    summary: "ปั๊มกุญแจ เปลี่ยนถ่านนาฬิกา ชั้น B1 หน้าลิฟต์ฝั่งเหนือ ก่อนถึงห้องน้ำ",
    knowhow: [
      "ปั๊มกุญแจสำรองไว้สักดอก ทำกุญแจหายตอนดึกจะได้ไม่ต้องนั่งรอหน้าห้อง",
      "ดอกที่ปั๊มแล้วไขไม่เข้า เอากลับไปให้ร้านแก้ได้",
      "โทรถามร้านได้ที่ 085-234-1214",
    ],
    cautions: ["ถามหอก่อนว่าปั๊มกุญแจห้องเองได้ไหม บางหอไม่ให้"],
    // Price is an estimate for a plain key.
    price: { min: 60, max: 150, per: "ต่อดอก", checked: { on: "2026-10", by: "ทีมตั้งหลัก", how: "web" } },
  },
];
